// Project: aguacongas/DymamicAuthProviders
// Copyright (c) 2021 @Olivier Lefebvre

// <auto-generated />
using Aguacongas.AspNetCore.Authentication.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aguacongas.AspNetCore.Authentication.Sample.Migrations.SchemeDb
{
    [DbContext(typeof(SchemeDbContext))]
    partial class SchemeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Aguacongas.AspNetCore.Authentication.SchemeDefinition", b =>
                {
                    b.Property<string>("Scheme")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("DisplayName");

                    b.Property<string>("SerializedHandlerType");

                    b.Property<string>("SerializedOptions");

                    b.HasKey("Scheme");

                    b.ToTable("Providers");
                });
#pragma warning restore 612, 618
        }
    }
}
